"use client"

import { useState } from "react"
import { BarChart3, ChevronLeft, ChevronRight } from "lucide-react"
import { HeroBanner } from "@/components/dashboard/hero-banner"
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, LabelList, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"

const months = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"]
const executionData = months.map((month, index) => ({ month, overall: [4, 7, 11.57, 18.4, 27.48, 35.38, 43.96, 46, 51, 58, 65, 76][index], previous: [3, 6, 10, 15, 22, 29, 37, 40, 44, 49, 55, 62][index], trend: [4, 7, 11.57, 18.4, 27.48, 35.38, 43.96, 39.57, 46.8, 51.65, 58, 76][index] }))
const budgetData = months.map((month, index) => ({ month, spending: [2.38, 3.88, 6.21, 9.89, 14.75, 18.99, 23.59, 27, 31, 35, 39, 43][index], deptSpending: [2.1, 3.4, 5.6, 8.5, 12.4, 16.5, 21.1, 24, 28, 31, 35, 38][index], techSpending: [0.43, 0.54, 0.91, 1.46, 3.96, 6.22, 8.4, 10, 12, 14, 16, 18][index], execution: [2.38, 7.22, 11.57, 18.42, 33.25, 42.06, 49.63, 55, 61, 66, 72, 78][index], deptExecution: [2, 6, 10, 16, 29, 38, 45, 51, 57, 62, 68, 74][index], techExecution: [1, 5, 9, 14, 25, 34, 42, 48, 54, 59, 65, 70][index] }))
const top10 = [["科技运维中心", 61742.92], ["科技管理部", 12937.86], ["信用卡中心", 4873.6], ["资金营运中心", 1481.65], ["金融科技研究院", 1189.38], ["运营管理部", 530.99], ["财富管理部", 471.41], ["资产托管部", 309.63], ["银行合作中心", 159.8], ["数字运营部", 145.02]] as const
const resourceTypes = [["服务", 7.24, "#356be4"], ["硬件", 4.74, "#8b8bea"], ["网络", 0.98, "#f3ae32"], ["软件", 0.96, "#e5796d"], ["机房", 0.56, "#a5a7ef"]] as const
const resourceRows = [["服务", "技术服务", "离岸技术服务", "3,350"], ["服务", "技术服务", "其他技术服务", "1,030"], ["服务", "技术服务", "大型型资源服务", "2,295"], ["服务", "咨询服务", "IT咨询服务", "216"], ["服务", "安全服务", "安全服务", "1,420"], ["服务", "研发服务", "研发现场技术服务", "3,835"], ["服务", "研发服务", "项目研发实施服务", "1,830"], ["硬件", "服务器", "通用服务器", "2,960"], ["硬件", "存储设备", "集中式存储", "1,280"], ["网络", "网络设备", "交换机设备", "980"], ["软件", "基础软件", "数据库软件", "960"], ["机房", "基础设施", "机房环境服务", "560"]] as const
const departments = ["资产托管部", "数据管理部", "科技运维中心", "金融科技研究院", "运营管理部", "财务管理部"]
const researchServiceRows = [["研发现场技术服务（B类）", "科技运维中心", "37,425.70"], ["项目研发实施服务（C类）", "信用卡中心", "356.07"], ["研发现场技术服务（B类）", "财富管理部", "226.04"], ["项目研发实施服务（C类）", "科技运维中心", "192.87"], ["研发现场技术服务（B类）", "银行合作中心", "159.80"], ["项目研发实施服务（C类）", "信用卡中心", "716.11"]] as const

function Panel({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`overflow-hidden rounded-xl border border-border/80 bg-card shadow-[0_8px_24px_oklch(0.35_0.06_240/8%)] ${className}`}><header className="flex items-center gap-2 border-b border-border/70 bg-gradient-to-r from-secondary/70 to-card px-3 py-2.5"><span className="flex size-7 items-center justify-center rounded-md bg-primary/10 text-primary"><BarChart3 className="size-4" /></span><h2 className="text-sm font-bold text-foreground">{title}</h2></header><div className="flex min-h-0 flex-1 flex-col p-3">{children}</div></section> }
const tooltipStyle = { backgroundColor: "#ffffff", color: "#0f172a", border: "1px solid #cbd5e1", borderRadius: 8, fontSize: 11, boxShadow: "0 6px 18px rgba(15, 23, 42, 0.14)" }
function ChartFrame({ children, height = 230 }: { children: React.ReactElement; height?: number }) { return <div style={{ height }} className="w-full"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div> }
function BudgetExecution() { return <div><ChartFrame><ComposedChart data={executionData} margin={{ top: 12, right: 10, bottom: 4, left: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="month" tick={{ fontSize: 11 }} /><YAxis domain={[0, 80]} tick={{ fontSize: 10 }} unit="%" /><Tooltip cursor={false} contentStyle={tooltipStyle} formatter={(value, name) => [`${Number(value).toFixed(2)}%`, name]} /><Legend verticalAlign="bottom" height={24} wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="overall" name="整体预算执行率" fill="#356be4" radius={[3, 3, 0, 0]} /><Bar dataKey="previous" name="上年执行率" fill="#8b8bea" radius={[3, 3, 0, 0]} /><Line type="monotone" dataKey="trend" name="执行率趋势" stroke="#f3ae32" strokeWidth={2} dot={{ r: 2 }} /></ComposedChart></ChartFrame></div> }
function BudgetLines({ department = false }: { department?: boolean }) { const data = budgetData.map((row) => department ? ({ ...row, spending: row.deptSpending, deptSpending: row.spending, techSpending: row.techSpending, execution: row.deptExecution, deptExecution: row.execution, techExecution: row.techExecution }) : row); return <ChartFrame><ComposedChart data={data} margin={{ top: 12, right: 10, bottom: 4, left: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="month" tick={{ fontSize: 11 }} /><YAxis yAxisId="amount" tick={{ fontSize: 10 }} /><YAxis yAxisId="rate" orientation="right" domain={[0, 100]} tick={{ fontSize: 10 }} unit="%" /><Tooltip cursor={false} contentStyle={tooltipStyle} /><Legend verticalAlign="bottom" height={24} wrapperStyle={{ fontSize: 10 }} /><Bar yAxisId="amount" dataKey="spending" name={department ? "总行部门列支" : "列支"} fill="#356be4" /><Bar yAxisId="amount" dataKey="deptSpending" name={department ? "总行部门列支（资本性）" : "总行部门列支"} fill="#8b8bea" /><Bar yAxisId="amount" dataKey="techSpending" name={department ? "总行部门列支（费用性）" : "数金技术服务费列支"} fill="#f3ae32" /><Line yAxisId="rate" type="monotone" dataKey="execution" name={department ? "总行部门预算执行率" : "预算执行率"} stroke="#e5796d" strokeWidth={2} /><Line yAxisId="rate" type="monotone" dataKey="deptExecution" name={department ? "总行部门预算执行率（资本性）" : "总行部门预算执行率"} stroke="#16a3a3" strokeWidth={2} /><Line yAxisId="rate" type="monotone" dataKey="techExecution" name={department ? "总行部门预算执行率（费用性）" : "数金技术服务费预算执行率"} stroke="#7b61c9" strokeWidth={2} /></ComposedChart></ChartFrame> }
function ResourceTable() { return <div className="h-[30rem] max-h-[30rem] overflow-auto overscroll-contain rounded-lg border border-border/70 bg-secondary/15"><table className="w-full min-w-0 table-fixed text-left text-[11px]"><colgroup><col className="w-[18%]" /><col className="w-[22%]" /><col className="w-[40%]" /><col className="w-[20%]" /></colgroup><thead className="sticky top-0 z-20 bg-card text-primary shadow-[0_2px_4px_hsl(var(--border)/55%)]"><tr>{["资源分类一级", "资源分类二级", "资源分类三级", "列支"].map((head) => <th key={head} className="bg-card border-b border-primary/20 px-2 py-2 font-bold"><span className="block whitespace-normal leading-4">{head}</span></th>)}</tr></thead><tbody className="divide-y divide-border/50">{resourceRows.map((row, rowIndex) => <tr key={row[2]} className={rowIndex % 2 ? "bg-card/60" : "bg-transparent"}>{row.map((cell, index) => <td key={index} className={`px-2 py-1.5 align-middle text-foreground ${index < 2 ? "whitespace-nowrap" : index === 2 ? "break-words font-medium leading-4" : "whitespace-nowrap text-right font-mono font-bold text-primary"}`}>{cell}</td>)}</tr>)}</tbody></table></div> }
function ResearchServiceTable() { return <div className="max-h-56 overflow-auto overscroll-contain rounded-lg border border-border/70 bg-secondary/15"><table className="w-full min-w-0 table-fixed text-left text-[11px]"><colgroup><col className="w-[46%]" /><col className="w-[30%]" /><col className="w-[24%]" /></colgroup><thead className="sticky top-0 z-20 bg-card text-primary shadow-[0_2px_4px_hsl(var(--border)/55%)]"><tr><th className="bg-card border-b border-primary/20 px-2 py-2 font-bold">资源分类三级</th><th className="bg-card border-b border-primary/20 px-2 py-2 font-bold">使用单位</th><th className="bg-card border-b border-primary/20 px-2 py-2 text-right font-bold">列支</th></tr></thead><tbody className="divide-y divide-border/50">{researchServiceRows.map((row, index) => <tr key={`${row[0]}-${row[1]}-${index}`} className={index % 2 ? "bg-card/60" : "bg-transparent"}>{row.map((cell, cellIndex) => <td key={cellIndex} className={`break-words px-2 py-2 text-foreground ${cellIndex === 0 ? "font-medium leading-4" : cellIndex === 2 ? "text-right font-mono font-bold text-primary" : ""}`}>{cell}</td>)}</tr>)}</tbody></table></div> }
function TopDepartments() { return <ChartFrame height={230}><BarChart layout="vertical" data={top10.map(([name, value]) => ({ name: name.replace("中心", ""), value }))} margin={{ top: 8, right: 48, bottom: 8, left: 82 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis type="number" tick={{ fontSize: 10 }} tickFormatter={(value) => `${value >= 10000 ? `${(value / 10000).toFixed(1)}万` : value}`} /><YAxis type="category" dataKey="name" width={78} tick={{ fontSize: 10 }} /><Tooltip cursor={false} contentStyle={tooltipStyle} formatter={(value) => [`${Number(value).toLocaleString()} 万元`, "列支"]} /><Bar dataKey="value" name="列支" fill="#356be4" activeBar={{ fill: "#7c3aed" }} radius={[0, 5, 5, 0]} barSize={15}><LabelList dataKey="value" position="right" formatter={(value: number) => `${value.toFixed(0)}万`} fill="hsl(var(--foreground))" fontSize={9} /></Bar></BarChart></ChartFrame> }
function ResourcePie() { const [selected, setSelected] = useState(0); const total = resourceTypes.reduce((sum, [, value]) => sum + value, 0); const [selectedName, selectedValue] = resourceTypes[selected]; return <div className="grid items-center gap-3 sm:grid-cols-[1fr_120px]"><div className="relative"><ChartFrame height={220}><PieChart><Pie data={resourceTypes.map(([name, value, color]) => ({ name, value, color }))} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={78} innerRadius={48} paddingAngle={2} onClick={(_, index) => setSelected(index)}>{resourceTypes.map(([name, , color], index) => <Cell key={name} fill={color} opacity={selected === index ? 1 : 0.62} stroke="hsl(var(--card))" strokeWidth={2} />)}</Pie><Tooltip cursor={false} contentStyle={tooltipStyle} formatter={(value) => [`${Number(value).toFixed(2)}亿元`, "列支"]} /></PieChart></ChartFrame><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="font-mono text-lg text-foreground">{selectedValue.toFixed(2)}</strong><span className="text-[10px] text-muted-foreground">{selectedName} · 亿元</span></div></div><div className="grid gap-1.5 text-[11px]">{resourceTypes.map(([name, value, color], index) => <button type="button" key={name} onClick={() => setSelected(index)} className={`flex items-center justify-between gap-2 rounded-md px-2 py-1.5 text-left transition ${selected === index ? "bg-primary/10 font-bold text-foreground" : "text-muted-foreground hover:bg-secondary/70"}`}><span className="flex items-center gap-2"><i className="size-2 rounded-full" style={{ backgroundColor: color }} />{name}</span><span className="font-mono">{((value / total) * 100).toFixed(1)}%</span></button>)}</div></div> }
function BudgetTable() { const rows = departments.map((name, index) => [name, index + 2, 1266 + index * 987, index % 4 + 1, index % 3 + 1, 49 - index]); return <div className="max-h-56 overflow-auto overscroll-contain rounded-lg border border-border/70 bg-secondary/15"><table className="w-full min-w-[620px] text-left text-[11px]"><thead className="sticky top-0 z-20 bg-card text-primary shadow-[0_2px_4px_hsl(var(--border)/55%)]"><tr>{["科技职能相关单位", "年度呈报预算项目数", "年度呈报预算金额（万元）", "已发起预算项目数", "已发起预算笔数", "已发起预算金额（万元）"].map((head) => <th key={head} className="bg-card border-b border-primary/20 px-2 py-2 font-bold leading-4"><span className="block whitespace-normal">{head}</span></th>)}</tr></thead><tbody className="divide-y divide-border/50">{rows.map((row, rowIndex) => <tr key={row[0]} className={rowIndex % 2 ? "bg-card/60" : "bg-transparent"}>{row.map((cell, index) => <td key={index} className={`px-2 py-2 text-foreground ${index === 0 ? "font-semibold" : "text-right font-mono"}`}>{typeof cell === "number" ? cell.toLocaleString() : cell}</td>)}</tr>)}</tbody></table></div> }
export function ResourceDashboard() { return <div className="min-h-screen bg-background px-4 pb-8 text-foreground md:px-6"><div className="mx-auto max-w-[1800px]"><HeroBanner title="资源管理驾驶舱" subtitle="" /><div className="mb-3 mt-3 rounded-lg border border-primary/20 bg-primary/5 px-4 py-2 text-lg font-black text-primary">科技投入（管理预算口径）</div><div className="grid gap-3 lg:grid-cols-12"><Panel className="lg:col-span-5" title="2026年预算整体执行率"><BudgetExecution /></Panel><Panel className="lg:col-span-4" title="预算列支情况（单位：亿元）"><BudgetLines /></Panel><Panel className="flex flex-col lg:col-span-3 lg:row-span-2" title="资源分类列支情况"><ResourceTable /></Panel><Panel className="lg:col-span-4" title="总行部门费用类型列支情况（单位：亿元）"><BudgetLines department /></Panel><Panel className="lg:col-span-5" title="总行部门列支情况（TOP10）"><TopDepartments /></Panel><Panel className="self-start lg:col-span-4" title="预算呈报情况"><BudgetTable /></Panel><Panel className="self-start lg:col-span-5" title="研发服务费机构分布情况"><ResearchServiceTable /></Panel><Panel className="lg:col-span-3" title="资源类型分布"><ResourcePie /></Panel></div></div></div> }
