"use client"

import { useState } from "react"
import { BarChart3, ChevronDown, ChevronUp } from "lucide-react"
import { HeroBanner } from "@/components/dashboard/hero-banner"

const palette = { blue: "#4ba8d8", violet: "#8494d8", teal: "#42bdb7", amber: "#e5b45c" }
const rolloutRows: Array<[string, number, number]> = [["操作系统", 420, 55.26], ["服务器", 180, 64.59], ["金融机具", 310, 38.64], ["数据库", 260, 73.04], ["网络设备", 225, 67.32], ["A4单色打印机", 198, 38.15], ["终端", 360, 61.2], ["存储", 142, 48.7]]
const branchRows: Array<[string, number, number]> = [["南京分行", 9, 5], ["苏州分行", 6, 3], ["北京分行", 6, 4], ["上海分行", 5, 3], ["青岛分行", 5, 2], ["福州分行", 9, 6], ["深圳分行", 4, 2], ["西安分行", 6, 4]]
const departmentRows: Array<[string, number, number]> = [["公司金融部\n数字支撑室", 4, 2], ["绿色金融部\n临客部", 4, 0], ["普惠金融部\n村镇服务", 4, 0], ["机构业务部", 5, 1], ["国际业务部\n贸易行管", 24, 9], ["投资银行部", 2, 1], ["零售金融部\n消费者权益保护办公室", 23, 8]]

function Panel({ title, children, className = "" }: { title: React.ReactNode; children: React.ReactNode; className?: string }) { return <section className={`overflow-hidden rounded-lg border border-border/80 bg-card shadow-[0_6px_18px_oklch(0.35_0.06_240/8%)] ${className}`}><header className="flex items-center gap-2 border-b border-border/70 bg-gradient-to-r from-secondary/70 to-card px-3 py-2"><span className="flex size-6 items-center justify-center rounded-md bg-primary/10 text-primary"><BarChart3 className="size-3.5" /></span><h2 className="min-w-0 truncate text-sm font-bold text-foreground">{title}</h2></header><div className="flex flex-1 flex-col p-3">{children}</div></section> }
function Donut({ value, label, total, color = palette.blue }: { value: number; label: string; total: string; color?: string }) { const circumference = 2 * Math.PI * 42; return <div className="flex min-h-[84px] items-center gap-2 rounded-lg border border-border/70 bg-secondary/25 p-2"><div className="relative size-[62px] shrink-0"><svg viewBox="0 0 100 100" className="size-full -rotate-90"><circle cx="50" cy="50" r="42" fill="none" stroke="currentColor" strokeWidth="12" className="text-secondary" /><circle cx="50" cy="50" r="42" fill="none" stroke={color} strokeWidth="12" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={circumference * (1 - value / 100)} /></svg><div className="absolute inset-0 flex items-center justify-center"><strong className="font-mono text-[13px] font-black text-foreground">{value.toFixed(1)}%</strong></div></div><div className="min-w-0"><p className="truncate text-xs font-semibold text-foreground">{label}</p><p className="mt-0.5 truncate font-mono text-base font-black text-primary">{total}</p></div></div> }
function ProductBars() { const max = Math.max(...rolloutRows.map(([, n]) => n)); return <div className="relative mb-7 ml-7 flex h-44 items-end gap-2 border-b border-l border-border px-2"><div className="absolute right-0 top-0 flex gap-2 text-[9px] text-muted-foreground"><span><i className="mr-1 inline-block size-1.5 rounded-sm bg-primary" />已替代</span><span><i className="mr-1 inline-block size-1.5 rounded-sm bg-secondary" />未替代</span></div>{rolloutRows.map(([name, amount, ratio]) => <div key={name} className="group relative flex min-w-0 flex-1 flex-col items-center justify-end"><div className="pointer-events-none absolute bottom-full z-10 mb-2 hidden w-32 rounded border border-border bg-card p-1.5 text-[10px] shadow-lg group-hover:block"><b>{name}</b><br />总量 {amount}，已替代 {Math.round(amount * ratio / 100)}</div><div className="flex w-3/5 flex-col justify-end" style={{ height: `${Math.max(18, amount / max * 125)}px` }}><div className="w-full rounded-t bg-primary" style={{ height: `${ratio}%` }} /><div className="w-full bg-secondary" style={{ height: `${100 - ratio}%` }} /></div><span className="absolute -bottom-6 max-w-full truncate text-[9px] text-muted-foreground">{name}</span></div>)}</div> }
function HorizontalBars() { const rows = [["对公核心", 66, 531], ["零售存款", 663, 1031], ["总账核算", 664, 859]]; return <div className="flex flex-col gap-4 py-1">{rows.map(([label, actual, plan]) => <div key={label}><div className="mb-2 flex justify-between text-sm font-semibold"><span>{label}</span><span className="font-mono text-muted-foreground">{actual}/{plan}</span></div><div className="h-3 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${actual / plan * 100}%` }} /></div></div>)}</div> }
function DetailTable({ title, rows, branch = false }: { title: string; rows: Array<[string, number, number]>; branch?: boolean }) { const [open, setOpen] = useState(false); return <Panel title={title}><button type="button" onClick={() => setOpen(v => !v)} className="flex items-center justify-between rounded-md border border-primary/30 bg-primary/5 px-3 py-2 text-left text-xs font-semibold text-primary hover:bg-primary/10"><span>点击查看{branch ? "分行" : "总行"}系统改造明细</span>{open ? <ChevronUp className="size-4" /> : <ChevronDown className="size-4" />}</button>{open && <div className="mt-3 max-h-56 overflow-y-auto rounded-md border border-border/60"><table className="w-full text-left text-xs"><thead className="sticky top-0 border-b border-border bg-card text-muted-foreground"><tr><th className="px-2 py-1.5">序号</th><th className="px-2 py-1.5">{branch ? "分行名称" : "所属部门"}</th><th className="px-2 py-1.5 text-right">总数</th><th className="px-2 py-1.5 text-right">剩余</th></tr></thead><tbody className="divide-y divide-border/60">{rows.map(([name, total, remaining], i) => <tr key={name}><td className="px-2 py-1.5 text-muted-foreground">{i + 1}</td><td className="whitespace-pre-line px-2 py-1.5 font-medium">{name}</td><td className="px-2 py-1.5 text-right font-mono">{total}</td><td className="px-2 py-1.5 text-right font-mono text-muted-foreground">{remaining}</td></tr>)}</tbody></table></div>}</Panel> }

export function TrustedDashboard() { return <main className="min-h-screen bg-background text-foreground"><div className="relative mx-auto max-w-[1800px] px-4 pb-8 md:px-6"><HeroBanner title="信创管理驾驶舱" subtitle="信创改造 · 国产替代 · 系统适配 · 平稳迁移" /><div className="grid min-w-0 gap-3 lg:grid-cols-12"><section className="col-span-12 rounded-xl border-2 border-primary/70 bg-card p-3"><div className="mb-3 border-b border-border pb-2"><h2 className="text-base font-black text-primary">一、系统改造</h2><p className="text-[11px] text-muted-foreground">一般系统、核心系统及总行/分行改造进展</p></div><div className="grid gap-3 lg:grid-cols-3"><Panel title="一般系统信创进度"><div className="grid gap-2 md:grid-cols-2"><Donut value={65.81} label="已单轨" total="412" /><Donut value={24.68} label="年度已完成" total="58" color={palette.violet} /></div></Panel><Panel title="核心系统信创进度"><HorizontalBars /></Panel><div className="grid gap-3"><DetailTable title="总行系统改造进展明细" rows={departmentRows} /><DetailTable title="分行系统改造进展明细" rows={branchRows} branch /></div></div></section><section className="col-span-12 rounded-xl border-2 border-primary/70 bg-card p-3"><div className="mb-3 border-b border-border pb-2"><h2 className="text-base font-black text-primary">二、产品替代</h2><p className="text-[11px] text-muted-foreground">国产产品替代与关键品类存量消减</p></div><div className="grid gap-3 lg:grid-cols-3"><Panel title="麒麟界面推广进度"><div className="grid gap-2 md:grid-cols-2"><Donut value={19.56} label="已推广" total="16.68K" color={palette.violet} /><Donut value={30.93} label="年度已推广" total="16.68K" color={palette.violet} /></div></Panel><Panel title="小型机下线进展"><div className="grid grid-cols-2 gap-2"><Donut value={86} label="尚未下线" total="1,152" /><Donut value={14} label="已下线" total="188" color={palette.amber} /></div></Panel><Panel title="其他关键品类产品存量替代进度"><p className="mb-2 text-xs font-semibold">各品类进度</p><ProductBars /></Panel></div></section><section className="col-span-12 rounded-xl border-2 border-primary/70 bg-card p-3"><div className="mb-3 border-b border-border pb-2"><h2 className="text-base font-black text-primary">三、国密改造和密评进度</h2><p className="text-[11px] text-muted-foreground">国密改造、密评任务整体进展</p></div><div className="grid gap-3 md:grid-cols-2"><Panel title="总体进度"><div className="grid grid-cols-2 gap-2"><div className="rounded-lg bg-secondary/60 p-3"><p className="text-xs font-bold">密评工作</p><p className="mt-1 font-mono text-2xl font-black text-primary">100</p><p className="text-[10px] text-muted-foreground">总数 · 已改造 <strong className="text-accent">30</strong></p></div><div className="rounded-lg bg-secondary/60 p-3"><p className="text-xs font-bold">国密改造</p><p className="mt-1 font-mono text-2xl font-black text-primary">80</p><p className="text-[10px] text-muted-foreground">总数 · 已改造 <strong className="text-accent">25</strong></p></div></div></Panel></div></section></div></div></main> }
